import { CHAMPIONS_FORMATS } from '@colleja/showdown';
import { loadValidatedTeam } from './fixtures';
import type { HeadlessBattleOptions } from './headless-battle';
import { deriveSeed } from './seeds';

export interface SmokeScenario {
  label: string;
  options: HeadlessBattleOptions;
}

const FIXTURE_FORMATS = [
  { key: 'singles', label: 'Individuales BSS Reg M-C' },
  { key: 'doubles', label: 'Dobles VGC Reg M-C' },
] as const;

const RANDOM_FORMATS = [
  { key: 'randomSingles', label: 'Aleatorio individuales' },
  { key: 'randomDoubles', label: 'Aleatorio dobles' },
] as const;

/** Battle with the two validated fixture teams in an official Champions format. */
export function fixtureScenario(
  baseSeed: string,
  key: (typeof FIXTURE_FORMATS)[number]['key'],
): SmokeScenario {
  const formatid = CHAMPIONS_FORMATS[key];
  const id = `fixture-${key}`;
  const label = FIXTURE_FORMATS.find((format) => format.key === key)?.label ?? key;
  return {
    label: `Fixtures · ${label}`,
    options: {
      formatid,
      seed: deriveSeed(baseSeed, id),
      p1: {
        name: 'Equipo A',
        team: loadValidatedTeam('equipo-a', formatid),
        aiSeed: deriveSeed(baseSeed, `${id}:p1`),
      },
      p2: {
        name: 'Equipo B',
        team: loadValidatedTeam('equipo-b', formatid),
        aiSeed: deriveSeed(baseSeed, `${id}:p2`),
      },
    },
  };
}

/** Battle with teams generated by Showdown from the Champions random-battle sets. */
export function randomScenario(
  baseSeed: string,
  key: (typeof RANDOM_FORMATS)[number]['key'],
  index: number,
): SmokeScenario {
  const id = `${key}-${index}`;
  const label = RANDOM_FORMATS.find((format) => format.key === key)?.label ?? key;
  return {
    label: `${label} #${index + 1}`,
    options: {
      formatid: CHAMPIONS_FORMATS[key],
      seed: deriveSeed(baseSeed, id),
      p1: {
        name: 'Bot 1',
        teamSeed: deriveSeed(baseSeed, `${id}:team1`),
        aiSeed: deriveSeed(baseSeed, `${id}:p1`),
      },
      p2: {
        name: 'Bot 2',
        teamSeed: deriveSeed(baseSeed, `${id}:team2`),
        aiSeed: deriveSeed(baseSeed, `${id}:p2`),
      },
    },
  };
}

export function buildScenarios(baseSeed: string, randomPerFormat: number): SmokeScenario[] {
  return [
    ...FIXTURE_FORMATS.map(({ key }) => fixtureScenario(baseSeed, key)),
    ...RANDOM_FORMATS.flatMap(({ key }) =>
      Array.from({ length: randomPerFormat }, (_, index) => randomScenario(baseSeed, key, index)),
    ),
  ];
}
